<a href="https://colab.research.google.com/github/weltonlopesdev/Exercicios-resolvidos-em-python/blob/main/welton_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Fazer programa que converte a velocidade de m/s para km/h. Dado: velocidade(m/s) = velocidade(km/h) * 3.6

ms = 0
km = 0

ms = float(input('Digite o valor da velocidade que deseja converter em KM/h'))

v = ms * 3.6

print('O valor da velocidade, convertida em KM/h é', +v)

Digite o valor da velocidade que deseja converter em KM/h10
O valor da velocidade, convertida em KM/h é 36.0


In [ ]:
#Fazer um programa em que o usuário digita o raio de uma circunferência e o programa imprime na tela o seu comprimento.

raio = 0

raio = int(input('Entre com o valor do raio em que deseja transformar em comprimento'))

c = 2 * 3.14 * raio

print('O valor do raio em comprimento é', +c)

Entre com o valor do raio em que deseja transformar em comprimento26
O valor do raio em comprimento é 163.28


In [ ]:
#Fazer um programa em que o usuário entra com um número e o programa imprime na tela seu antecessor e seu sucessor.

num = int(input('Digite um numero'))
print('seu numero é', +num)
ant_num = num - 1
print('seu antecessor', +ant_num)

Digite um numero10
seu numero é 10
seu antecessor 9


In [ ]:
#Fazer um programa em que o usuário entra com o ano de seu nascimento e o programa imprime na tela ssua idade.

ano_atual = 2023
ano_nasc = int(input('Digite o ano de seu nascimento'))

result = ano_atual - ano_nasc

print('Você tem', +result, 'anos')






Digite o ano de seu nascimento2000
Você tem 23 anos


In [ ]:
#Escreva um programa que recebe 2 valores e devolve o maior entre eles.

num1 = int(input('Digite o primeiro numero'))
num2 = int(input('Digite o segundo numero'))

if num1 > num2:
  print('O numero maior é ', +num1)
if num2 > num1:
  print('O numero maior é ', +num2)

Digite o primeiro numero20
Digite o segundo numero2
O numero maior é  20


In [ ]:
#CALCULAR: Cada laranja custa R$ 0,3, mais quando comprada + de 1 duzia seu valor cai para 0,25 cada 

qtd_laranja = int(input('digite a quantidade de laranjas que deseja comprar e informaremos o preço em R$'))

if qtd_laranja > 12:
  preco_laranja_desc = qtd_laranja * 0.25
  print('O valor a ser pago pelas', +qtd_laranja, 'é:', 'R$', +preco_laranja_desc)
else:
  preco_laranja_normal = qtd_laranja * 0.30
  print('O valor a ser pago pelas', +qtd_laranja, 'é:', 'R$', +preco_laranja_normal)

digite a quantidade de laranjas que deseja comprar e informaremos o preço em R$89
O valor a ser pago pelas 89 é: R$ 22.25


In [ ]:
#Fazer uma calculadora em que o usuário digita Altura em metros e Peso em quilos.
# O programa devolve ao usuário a informação qual seu peso ideal. 

# com altura de 1,60 m, o peso ideal 52 kg a 64 kg.
# com altura de 1,70 m, o peso ideal 65 kg a 72 kg.
# com altura de 1,80 m, o peso ideal 72 kg a 82 kg.
# com altura de 1,90 m, o peso ideal 82 kg a 92 kg.


altura = float(input('Digite a sua altura'))
peso = int(input('digite seu peso'))

if altura == 1.60 and peso <=52:
  print('Você está abaixo do peso para sua altura')
if altura == 1.60 and peso >52 and peso <=64:
  print('Você está no peso ideal para sua altura')

if altura == 1.70 and peso >65 and peso <=71:
  print('Você está no peso ideal para sua altura')

if altura == 1.80 and peso >72 and peso <=81:
  print('Você está no peso ideal para sua altura')

if altura == 1.90 and peso >82 and peso <=92:
  print('Você está no peso ideal para sua altura')

if altura > 1.90 and peso > 92:
  print('Não temos dados para saber se o peso está de acordo com a altura')



Digite a sua altura1.60
digite seu peso52
Você está abaixo do peso para sua altura


In [ ]:
#Para determinar se 3 segmentos de reta formam um triângulo, podemos fazer a verificação se a soma dos dois menores segmentos é maior do que o segmento maior.

#Segmentos: 2, 3 e 4
#Soma dos dois menores: 2 + 3 = 5
#Verificação: 5 > 4
#Conclusão:Estes segmentos formam um triângulo


seg1 = int(input('digite os valorer do segmento 1 :' ))
seg2 = int(input('digite os valorer do segmento 2 :' ))
seg3 = int(input('digite os valorer do segmento 3 :' ))

if seg1 + seg2 > seg3 and seg1 + seg3 > seg2 and seg2 + seg3 > seg1:
  print('Estes segmentes formam um triangulo')
else:
  print('não forma um triangulo')
  







digite os valorer do segmento 1 :1
digite os valorer do segmento 2 :0
digite os valorer do segmento 3 :0
não forma um triangulo


In [ ]:
#DESAFIO

#Um posto de gasolina está vendendo combustíveis com a seguinte tabela de descontos: 

#Gasolina:
#Até 20 litros: desconto de 4% por litro
#Acima de 20 litros: desconto de 6% por litro

#Álcool:
#Até 20 litros: desconto de 3% por litro
#Acima de 20 litros: desconto de 5% por litro

#Escreva um programa que leia o tipo de combustível (A - Álcool e G - Gasolina), calcule e imprima o valor a ser pago pelo cliente.

import random

op = False
esc = False

print('Deseja abastecer com Gasolina ou Alcool? (g : para Gasolina e a: para Alcool):')
v = input()

if v != 'a' and v != 'g':
  while esc == False:
    print('Escreva corretamente, a ou g)')
    v = input()
    if v != 'a' or v != 'g':
      esc = False
    if v == 'a' or v == 'g':
      esc = True
      break

 #Quando escolhe a Gasolina 
if v == 'g':
    x = list(range(1,53))
    print(x)
    print('Escolha um numero de 1 a 52 (obs: 1 equivale a 1 LITRO  :')
    g = int(input())
    while op == False:
      if g >= 1 and g <= 20:
        sem_desc = g * 5.51
        desc = sem_desc * 0.04
        com_desc = sem_desc - desc
        op = True
      if g > 21:
        sem_desc = g * 5.51
        desc = sem_desc * 0.06
        com_desc = sem_desc - desc
        op = True
      if g < 1:
        op = False
        print('Digite um valor de 1 a 52, não sairá enquanto não digitar corretamente  :)')
        g = int(input())
    print(f"Gasolina sem desconto: R${sem_desc:.2f}")
    print(f"Desconto: R${desc:.2f}")
    print(f"O valor a ser pago na Gasolina é R${com_desc:.2f}")


 #Caso o cliente escolheu Alcool
if v == 'a':
    x = list(range(1,53))
    print(x)
    print('Escolha um numero de 1 a 52 (obs: 1 equivale a 1 LITRO  :')
    a = int(input())
    while op == False:
      if a >= 1 and a <= 20:
        sem_desc = a * 4.31
        desc = sem_desc * 0.03
        com_desc = sem_desc - desc
        op = True
      if a > 21:
        sem_desc = g * 5.51
        desc = sem_desc * 0.05
        com_desc = sem_desc - desc
        op = True
      if a < 1:
        op = False
        print('Digite um valor de 1 a 52, não sairá enquanto não digitar corretamente  :)')
    print(f"Alcool sem desconto: R${sem_desc:.2f}")
    print(f"Desconto: R${desc:.2f}")
    print(f"O valor a ser pago no Alcool é R${com_desc:.2f}")






Deseja abastecer com Gasolina ou Alcool? (g : para Gasolina e a: para Alcool):
a
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52]
Escolha um numero de 1 a 52 (obs: 1 equivale a 1 LITRO  :
57
Alcool sem desconto: R$308.56
Desconto: R$15.43
O valor a ser pago no Alcool é R$293.13


In [ ]:
#Faça um programa que pergunte quanto vc ganha por hora e o numero de horas trabalhadas no mês, calcule e mostre o total do seu salario por mês
#jornada mensal: 220 horas;

print('Quanto você ganha por hora?')
quantHoras = int(input())
print('Quantas horas trabalhadas no mês?')
quantHorasMes = int(input())
salario = quantHoras * quantHorasMes

print(f"Vocês recebe este salário por MÊS :  R$ {salario:.2f}")

Quanto você ganha por hora?
20
Quantas horas trabalhadas no mês?
220
Vocês recebe este salário por MÊS :  R$ 4400.00


In [ ]:
# LISTAS EM PYTHON
#retorne a quantidade de itens da lista

l = [1,2,3,4,5]
len(l)

5

In [ ]:
#retorne o menor valor da lista
a = [1,2,3,4,5]
min(a)

1

In [ ]:
#retorne o maior valor da lista
b = [1,2,3,4,5]
max(b)

5

In [ ]:
#soma todos os valores da lista
s = [1,2,3,4,5]
sum(s)

15

In [ ]:
#adiciona novo valor da lista
s = [1,2,3,4,5]
s.append(100)
print(s)

[1, 2, 3, 4, 5, 100]


In [ ]:
#insere uma lista no final de outra lista
s = [1,2,3,4,5]
print(s)
s.extend([6,7,8])
print(s)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
#remove um elemento da lista

n = [1,2,3,4,5]
del n[2]
print(b)

[1, 3, 4, 5]


In [ ]:
#verifica se um valor pertence à lista
v = [1,2,3,4,5]

3 in v


True

In [ ]:
#ordena em ordem crescente

t = [6,7,89,0,-7]

t.sort()
print(t)

[-7, 0, 6, 7, 89]


In [ ]:
#inverte os elementos de uma lista.

g = [1,2,3,4,5]

g.reverse()
print(g)

[5, 4, 3, 2, 1]


In [ ]:
#Concatenação de 2 listas

a = [0,1,2]
b = [0,9,8,6,7]

c = a + b
print(c)

[0, 1, 2, 0, 9, 8, 6, 7]


In [ ]:
#cria uma lista com n vezes os elementos da original

m = [0,1,2]

r = m * 10
print(r)

[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]


In [ ]:
#fatiamento de listas

L = [3 , 'abacate' , 9.7 , [5 , 6 , 3] , "Python" , (3 , 'j')] 

j = L[1:3]
print(j)
o = L[1:4]
print(o)
e = L[1:5]
print(e)


['abacate', 9.7]
['abacate', 9.7, [5, 6, 3]]
['abacate', 9.7, [5, 6, 3], 'Python']


In [ ]:
#Criar lista com função range

L1 = list(range(5))
print(L1)

[0, 1, 2, 3, 4]


In [ ]:
#Faça um programa que receba a temperatura média de cada mês do ano e armazene-as em uma lista.
#Após isto, calcule a média anual das temperaturas e mostre todas as temperaturas acima da média anual, e em que mês elas ocorreram

#(mostrar o mês por extenso: 1 – Janeiro, 2 – Fevereiro, . . . ).

temp = []
mes = ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', ' Novembro', 'Dezembro']

print('Calcular a temperatura média de cada mês do ano')

j = int(input(f"Digite a temperatura do mês de : {mes[0]} :"))
temp.append(j)
f = int(input(f"Digite a temperatura do mês de : {mes[1]} :"))
temp.append(f)
m = int(input(f"Digite a temperatura do mês de : {mes[2]} :"))
temp.append(m)
a = int(input(f"Digite a temperatura do mês de : {mes[3]} :"))
temp.append(a)
ma = int(input(f"Digite a temperatura do mês de : {mes[4]} :"))
temp.append(ma)
jun = int(input(f"Digite a temperatura do mês de : {mes[5]} :"))
temp.append(jun)
jul = int(input(f"Digite a temperatura do mês de : {mes[6]} :"))
temp.append(jul)
ag = int(input(f"Digite a temperatura do mês de : {mes[7]} :"))
temp.append(ag)
sete = int(input(f"Digite a temperatura do mês de : {mes[8]} :"))
temp.append(sete)
out = int(input(f"Digite a temperatura do mês de : {mes[9]} :"))
temp.append(out)
nov = int(input(f"Digite a temperatura do mês de : {mes[10]} :"))
temp.append(nov)
dez = int(input(f"Digite a temperatura do mês de : {mes[11]} :"))
temp.append(dez)


media = sum(temp) / len(temp) # calculado a média
print(f"A média anual das temperaturas é:{media:.2f}")

for i in temp:
  if temp[i] > media:
    temp_maior_media = temp[i]
    for o in mes:
      mes_maior_media = mes[i]
    print(f"Esta é a temperatura maior que a média anual : {temp_maior_media} Mes de :  {mes_maior_media}")







Calcular a temperatura média de cada mês do ano
Digite a temperatura do mês de : Janeiro :1
Digite a temperatura do mês de : Fevereiro :2
Digite a temperatura do mês de : Março :3
Digite a temperatura do mês de : Abril :2
Digite a temperatura do mês de : Maio :1
Digite a temperatura do mês de : Junho :5
Digite a temperatura do mês de : Julho :2
Digite a temperatura do mês de : Agosto :1
Digite a temperatura do mês de : Setembro :4
Digite a temperatura do mês de : Outubro :5
Digite a temperatura do mês de :  Novembro :2
Digite a temperatura do mês de : Dezembro :4
A média anual das temperaturas é:2.67
Esta é a temperatura maior que a média anual : 3 Mes de :  Março
Esta é a temperatura maior que a média anual : 3 Mes de :  Março
Esta é a temperatura maior que a média anual : 5 Mes de :  Junho
Esta é a temperatura maior que a média anual : 3 Mes de :  Março
Esta é a temperatura maior que a média anual : 5 Mes de :  Junho
Esta é a temperatura maior que a média anual : 3 Mes de :  Março


In [ ]:
#DICIONÁRIOS EM PYTHON
#imprimindo 
precos = {'lapis': 5.5, 'borracha': 7.0, 'caneta': 6.5}
print(precos)

{'lapis': 5.5, 'borracha': 7.0, 'caneta': 6.5}


In [ ]:
#imprimindo apenas um trecho 

print("preco da borracha é:", precos['borracha'])

preco da borracha é: 7.0


In [ ]:
#deletando um item do dicionário

preco = {'lapis': 5.5, 'borracha': 7.0, 'caneta': 6.5}
print(preco)
del preco['caneta']
print(preco)

{'lapis': 5.5, 'borracha': 7.0, 'caneta': 6.5}
{'lapis': 5.5, 'borracha': 7.0}


In [ ]:
#verificar se uma chave exste no dicionário

'borracha' in preco

True

In [ ]:
#Obtém as chaves de um dicionário. 

preco.keys()


dict_keys(['lapis', 'borracha'])

In [ ]:
#Obtém as chaves de um dicionário. 

preco.values()

dict_values([5.5, 7.0])

In [ ]:
#SETS EM PYTHON
#imprimindo um set

numeros = [1,2,3,4,5,6,7]
print(numeros)

[1, 2, 3, 4, 5, 6, 7]


In [ ]:
#adicionando um set


num = {1,2}
print(num)
mais_num = {3,4,5,6}
num.update(mais_num)
print(num)

{1, 2}
{1, 2, 3, 4, 5, 6}


In [ ]:
#TUPLAS
#imprimindo uma tupla

tp1 = (1,2,3,4,5)
print(tp1)

(1, 2, 3, 4, 5)


In [ ]:
#criando dicionários com tuplas

d = {(0,1): 0, (1,2):1}
# Cria dicionários com tuplas como chaves
print(d)

{(0, 1): 0, (1, 2): 1}


In [ ]:
#FUNÇÕES

#inprimindo uma função

def funcao():
  print("Hello World")

funcao()
funcao()
funcao()
funcao()

Hello World
Hello World
Hello World
Hello World


In [ ]:

#imprimindo uma função com chamada com parametro

def funcao2(msg):
  print(msg)
funcao2("Mensagem")

Mensagem


In [ ]:

#imprimindo uma função com chamada com 2 parametro

def funcao3(msg, nome):
  print(msg, nome)
funcao3("olá", "teste")
funcao3("olá", "teste2")
funcao3("olá", "teste3")

olá teste
olá teste2
olá teste3


In [ ]:
#função com return e parametro


def divide(n1,n2):
 return n1 / n2

divide(4,5)

#n1 = 4 e n2 = 5

0.8

In [ ]:

# função para determinar se a pessoa é adulta apartir do ano de nascimento e do ano atual
#SEM PASSAR NENHUM PARAMETRO

def calcular_data():
  data_atual = 2023
  data_nascimento = int(input("Digite o ano de nascimento"))
  if data_nascimento > data_atual:
    return f'Vocês ainda não nasceu.'
  if data_nascimento == data_atual:
    return f'Você nasceu este ano'
  if data_atual - data_nascimento >= 30:
    return f'Você é adulto'
  if data_atual - data_nascimento < 30:
    return f'Você ainda não é adulto'

calcular_data()


Digite o ano de nascimento1989


'Você é adulto'

In [ ]:
# função para determinar se a pessoa é adulta apartir do ano de nascimento e do ano atual
#PASSANDO UM PARAMETRO

def calcular_data2(data_nascimento):
  data_atual = 2023
  if data_nascimento > data_atual:
    return f'Vocês ainda não nasceu.'
  if data_nascimento == data_atual:
    return f'Você nasceu este ano'
  if data_atual - data_nascimento >= 30:
    return f'Você é adulto'
  if data_atual - data_nascimento < 30:
    return f'Você ainda não é adulto'

calcular_data2(1989)

'Você é adulto'

In [ ]:
#NUMPY
#cria uma matriz unidimencional
import numpy as np
a = np.array([12,34,35,36,37])  

print(a)
print(a.dtype)


[12 34 35 36 37]
int64


In [ ]:
#cria uma matrix bidimensional
import numpy as np

b = np.array([[7,2,3,4], [12,23,34,35], [5,34,23,25]])

print(b)
print(b.dtype)

[[ 7  2  3  4]
 [12 23 34 35]
 [ 5 34 23 25]]
int64


In [ ]:
#cria uma matrix 4x 3 com zeros
import numpy as np

d = np.zeros([4,3])

print(d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#array com numero aleatórios
import numpy as np

g = np.random.random((5))
print(g)


[0.92790985 0.28790185 0.51776854 0.25315545 0.39217568]


In [ ]:
#array com numero aleatórios negativos
import numpy as np

g2 = np.random.randn((5))
print(g2)



[ 0.28766357  0.50955981  1.42594433  0.58082145 -0.14024375]


In [ ]:
#array multidimensional retornando valor absoluto com floor
import numpy as np

h = np.floor(10*np.random.random((3,4)))
print(h)
print('-------------------------------')
y = np.floor(h)
print(y)

[[8. 8. 0. 8.]
 [9. 2. 7. 5.]
 [7. 9. 2. 0.]]
-------------------------------
[[8. 8. 0. 8.]
 [9. 2. 7. 5.]
 [7. 9. 2. 0.]]


In [ ]:
#array com numeros sem repetição
import numpy as np

k = np.random.random(10)
j = np.unique(k)
print(j)
print('-------------------------------')
print(k.shape) #mostra o tamanho das dimensões do array


[0.1154477  0.49374044 0.56909912 0.57183605 0.63750516 0.69413648
 0.75584112 0.75670924 0.86072027 0.93814195]
-------------------------------
(10,)


In [ ]:
#rearranja um conjunto de 15 elementos de 0 a 14 em 3 linhas e 5 colunas.
import numpy as np

r = np.arange(15).reshape((3,5))
print(r)
print('-------------------------------')
s = r.T
print(s)# mostra a matrizes transposta entre linha e coluna

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-------------------------------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [ ]:
#expressões lógicas em array. O NumPy nos fornece a função “where” que substitui um laço condicional if-else.
import numpy as np

v = np.random.randn(4,5) # criando matriz com valores aleatórios positivos e negativos
print(v)

print('-------------------------------')

x = (v > 0) #criando matriz com valores booleanos baseado no array v
print(x)

print('-------------------------------')

z = np.where(x > 0, 1, -1) # criando matriz com valores -1 e 1 baseado nos valores do array x
print(z)

[[-1.04402710e+00 -1.41906875e+00  1.59760831e+00  6.08144522e-01
   5.36267484e-04]
 [-2.11930854e-01 -3.83165314e-01  1.21497834e+00  1.09143304e+00
  -6.45178957e-01]
 [-9.82328076e-01 -1.69931356e+00 -7.47232672e-01 -7.19095563e-01
  -3.97664492e-01]
 [ 3.50210311e-01 -3.87112875e-01  8.48507112e-01  6.39076795e-01
   2.21920213e-01]]
-------------------------------
[[False False  True  True  True]
 [False False  True  True False]
 [False False False False False]
 [ True False  True  True  True]]
-------------------------------
[[-1 -1  1  1  1]
 [-1 -1  1  1 -1]
 [-1 -1 -1 -1 -1]
 [ 1 -1  1  1  1]]


In [ ]:
#desenvolva uma função que recebe um array de inteiros e retorne o mesmo array,
#porém ordenado em ordem crescente (sort()).
#No programa principal, gere um array de 15 números aleatórios,

import numpy as np


def sort():
  a = np.random.randint(0, 15, size=15) #gera o array
  b = np.sort(a) #ordena em ordem crescente
  return b

sort()

array([ 0,  0,  1,  4,  5,  6,  7,  9,  9, 10, 10, 12, 12, 12, 13])

In [ ]:
#PANDAS
#importando arquivos com pandas
import pandas as pd
from google.colab import files

uploaded = files.upload()



Saving dados.xlsx to dados.xlsx


In [ ]:
#verificando os arquivos que já subi
import pandas as pd

for fn in uploaded.keys():
  print('arquivo"{name}" com tamanho de {length} bytes' .format(name=fn, length=len(uploaded[fn])))

arquivo"dados.xlsx" com tamanho de 7708 bytes


In [ ]:
#ler o arquivo importado
import pandas as pd

dados = pd.read_excel('dados.xlsx')
print(dados)

   números letras
0        1      a
1        2      b
2        3      c
3        4      d
4        5      e
5        6      f
6        7      g
7        8      h
8        9      i
9       10      j


In [ ]:
#O “shape” que mostra uma tupla com o número de linhas e colunas do arquivo,

dados.shape


(10, 2)

In [ ]:
#e “head” que mostra os primeiros registros do dataset.
dados.head()

números letras
0        1      a
1        2      b
2        3      c
3        4      d
4        5      e

In [ ]:
#mostrando a quantidade solicitada

dados.head(8)

números letras
0        1      a
1        2      b
2        3      c
3        4      d
4        5      e
5        6      f
6        7      g
7        8      h

In [4]:
#carregando um CSV
import pandas as pd
from google.colab import files

uploaded = files.upload()


Saving census.csv to census.csv


In [5]:
#lendo o arquivo e mostrando o dataset

dados2 = pd.read_csv('census.csv')
dados2.head()

Unnamed: 0  age          workclass  final.weight   education  \
0           1   39          State-gov         77516   Bachelors   
1           2   50   Self-emp-not-inc         83311   Bachelors   
2           3   38            Private        215646     HS-grad   
3           4   53            Private        234721        11th   
4           5   28            Private        338409   Bachelors   

   education.num       marital.status          occupation    relationship  \
0             13        Never-married        Adm-clerical   Not-in-family   
1             13   Married-civ-spouse     Exec-managerial         Husband   
2              9             Divorced   Handlers-cleaners   Not-in-family   
3              7   Married-civ-spouse   Handlers-cleaners         Husband   
4             13   Married-civ-spouse      Prof-specialty            Wife   

     race      sex  capital.gain  capital.loos  hour.per.week  native.country  \
0   White     Male          2174             0             40   United-States   
1   White     Male             0             0             13   United-States   
2   White     Male             0             0             40   United-States   
3   Black     Male             0             0             40   United-States   
4   Black   Female             0             0             40            Cuba   

   income  
0   <=50K  
1   <=50K  
2   <=50K  
3   <=50K  
4   <=50K

In [ ]:
#CRIANDO DATAFRAME COM DICIONÁRIOS
import pandas as pd

alunos = {'nome':['marcelo', 'lucas', 'cintia'], 'media':[4,5,6], 'status':['reprovado', 'aprovado', 'aprovado']}

df = pd.DataFrame(alunos)
df.head()



nome  media     status
0  marcelo      4  reprovado
1    lucas      5   aprovado
2   cintia      6   aprovado

In [ ]:
#descrição dataset

dados.describe()
dados2.describe()


Unnamed: 0           age  final.weight  education.num  capital.gain  \
count  30162.000000  30162.000000  3.016200e+04   30162.000000  30162.000000   
mean   16288.103242     38.437902  1.897938e+05      10.121312   1092.007858   
std     9383.401676     13.134665  1.056530e+05       2.549995   7406.346497   
min        1.000000     17.000000  1.376900e+04       1.000000      0.000000   
25%     8179.250000     28.000000  1.176272e+05       9.000000      0.000000   
50%    16286.500000     37.000000  1.784250e+05      10.000000      0.000000   
75%    24402.750000     47.000000  2.376285e+05      13.000000      0.000000   
max    32561.000000     90.000000  1.484705e+06      16.000000  99999.000000   

       capital.loos  hour.per.week  
count  30162.000000   30162.000000  
mean      88.372489      40.931238  
std      404.298370      11.979984  
min        0.000000       1.000000  
25%        0.000000      40.000000  
50%        0.000000      40.000000  
75%        0.000000      45.000000  
max     4356.000000      99.000000

In [ ]:
# filtrando o dataset

dados2[['age']]

age
0       39
1       50
2       38
3       53
4       28
...    ...
30157   27
30158   40
30159   58
30160   22
30161   52

[30162 rows x 1 columns]

In [ ]:
#filtrar usando o loc

dados.loc[[1,3]]

números letras
1        2      b
3        4      d

In [ ]:
#estabelencendo condições

dados.loc[dados['números']==1]

números letras
0        1      a

In [ ]:
#Filtrando mais

dados.loc[(dados['números'] < 2) & (dados['letras']=='b')]

Empty DataFrame
Columns: [números, letras]
Index: []

In [ ]:
#séries a partir de listas de Python para dataframes
import pandas as pd

s1 = pd.Series([2,5,6,7,3,4,6,7,8])
print(s1)



0    2
1    5
2    6
3    7
4    3
5    4
6    6
7    7
8    8
dtype: int64


In [ ]:
#Series a partir de array numpy
import numpy as np
import pandas as pd

arrayS = np.array([2,4,6,8,9,3,4,5,6])
s2 = pd.Series(arrayS)
print(s2)

0    2
1    4
2    6
3    8
4    9
5    3
6    4
7    5
8    6
dtype: int64


In [10]:
#ler o csv e dropar a coluna com DROP

dados2 = pd.read_csv('census.csv')
dados2.head()
dados2.drop('age', axis=1)
dados2.head()


Unnamed: 0  age          workclass  final.weight   education  \
0           1   39          State-gov         77516   Bachelors   
1           2   50   Self-emp-not-inc         83311   Bachelors   
2           3   38            Private        215646     HS-grad   
3           4   53            Private        234721        11th   
4           5   28            Private        338409   Bachelors   

   education.num       marital.status          occupation    relationship  \
0             13        Never-married        Adm-clerical   Not-in-family   
1             13   Married-civ-spouse     Exec-managerial         Husband   
2              9             Divorced   Handlers-cleaners   Not-in-family   
3              7   Married-civ-spouse   Handlers-cleaners         Husband   
4             13   Married-civ-spouse      Prof-specialty            Wife   

     race      sex  capital.gain  capital.loos  hour.per.week  native.country  \
0   White     Male          2174             0             40   United-States   
1   White     Male             0             0             13   United-States   
2   White     Male             0             0             40   United-States   
3   Black     Male             0             0             40   United-States   
4   Black   Female             0             0             40            Cuba   

   income  
0   <=50K  
1   <=50K  
2   <=50K  
3   <=50K  
4   <=50K

In [ ]:
#verificando se a dados null e imprimindo eles

nulos = dados2.isnull()
print(nulos)

In [12]:
#verificando se a dados null e somando /impriindo

qtdnulos = dados2.isnull().sum()
print(qtdnulos)

Unnamed: 0        0
age               0
workclass         0
final.weight      0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loos      0
hour.per.week     0
native.country    0
income            0
dtype: int64


In [13]:
#percentual disso considerando o total de linhas utilizando o len

len(dados2['age'])

30162

In [14]:
#deletando uma coluna no caso a coluna "age" do arquivo

del dados2['age']
dados2.head()

Unnamed: 0          workclass  final.weight   education  education.num  \
0           1          State-gov         77516   Bachelors             13   
1           2   Self-emp-not-inc         83311   Bachelors             13   
2           3            Private        215646     HS-grad              9   
3           4            Private        234721        11th              7   
4           5            Private        338409   Bachelors             13   

        marital.status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital.gain  capital.loos  hour.per.week  native.country  income  
0          2174             0             40   United-States   <=50K  
1             0             0             13   United-States   <=50K  
2             0             0             40   United-States   <=50K  
3             0             0             40   United-States   <=50K  
4             0             0             40            Cuba   <=50K